language: php
env:
    global:
        - MIN_PHP=7.1.3
php:
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - mongodb

before_install:
  - pecl install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
install: composer install --prefer-dist

script: phpunit -c ./phpunit.xml.dist

notifications:
  email: false

