language: php
#matrix:
  #include:
    #- php: 7.1
      #env: SYMFONY_VERSION=^4.1 NO_X_DEBUG=true
    #- php: nightly
      #env: SYMFONY_VERSION=^4.1 NO_X_DEBUG=true
php:
  - '7.1'
  - 'nightly'

services:
  - mongodb
#before_install:
  #- if [ "$NO_X_DEBUG" != "" ]; then phpenv config-rm xdebug.ini; fi;
  #- if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  #- if [ "$TEST_SUITE" == "ORM" ]; then composer require doctrine/doctrine-bundle:^1.0 doctrine/orm:^2.0 --no-update; export PHPUNIT_FILE=./phpunit_orm.xml.dist; fi;
  #- if [ "$TEST_SUITE" == "ODM" ]; then composer require doctrine/mongodb-odm-bundle:^3.0 --no-update; export PHPUNIT_FILE=./phpunit_odm.xml.dist; fi;
  #- if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TEST_SUITE" == "ODM" ]; then phpenv config-add travis-php.ini; fi;
install: composer install --prefer-dist
script: phpunit -c ./phpunit.xml.dist
notifications:
  email: false

