language: php
env:
    global:
        - MIN_PHP=7.1.3
php:
  - '7.1'
  - '7.2'
  - '7.3'
cache:
  directories:
    - cached
services:
  - mongodb

before_install:
  - pecl install mongodb || true && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
install: composer install --prefer-dist
before_script: "[ -e cached/phpunit.phar ] || wget -O cached/phpunit.phar https://phar.phpunit.de/phpunit-7.phar && chmod u+x cached/phpunit.phar"
script: cached/phpunit.phar -c ./phpunit.xml.dist

notifications:
  email: false

