<?php

namespace Ordermind\LogicalAuthorizationDoctrineMongoBundle\Tests\Fixtures\Repository\User;

/**
 * TestUserRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestUserRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{
}
