<?php

namespace Ordermind\LogicalAuthorizationDoctrineMongoBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestDocumentWithParamsRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestDocumentWithParamsRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{
  public function customMethod() {
    return $this->findAll();
  }
}
