<?php

namespace Ordermind\LogicalAuthorizationDoctrineMongoBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestDocumentAbortDeleteRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestDocumentAbortDeleteRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{

}
