<?php

namespace Ordermind\LogicalAuthorizationDoctrineMongoBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestDocumentRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestDocumentRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{
    public function findByField1($value)
    {
        return $this->findBy(array('field1' => $value));
    }
    public function findOneByField1($value)
    {
        return $this->findOneBy(array('field1' => $value));
    }
}
