<?php

namespace Ordermind\LogicalAuthorizationDoctrineMongoBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestDocumentAbortSaveRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestDocumentAbortSaveRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{
}
